import type { Cat } from './types';

// Sample cats for development - will be replaced by Supabase data
export const sampleCats: Cat[] = [
  {
    id: '1',
    name: 'Marmalade',
    photos: ['/cats/cat1.jpg'],
    primary_photo: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400',
    location_lat: 35.8989,
    location_lng: 14.5146,
    location_name: 'Valletta Old Town',
    breed: 'Ginger Tabby',
    color: 'Orange',
    age: '~3 years',
    is_stray: true,
    background_story: 'Found lounging near the Grand Harbour, this friendly fellow greets every tourist with a meow.',
    voting_status: 'complete',
    voting_round_id: null,
    created_at: '2024-01-15T10:00:00Z',
    approved: true,
  },
  {
    id: '2',
    name: null,
    photos: ['/cats/cat2.jpg'],
    primary_photo: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=400',
    location_lat: 35.8617,
    location_lng: 14.4583,
    location_name: 'Mdina Gate',
    breed: 'Mixed',
    color: 'Black and White',
    age: '~2 years',
    is_stray: true,
    background_story: 'A mysterious tuxedo cat who watches over the ancient city gates.',
    voting_status: 'voting',
    voting_round_id: 'round-1',
    created_at: '2024-01-20T14:30:00Z',
    approved: true,
  },
  {
    id: '3',
    name: 'Luna',
    photos: ['/cats/cat3.jpg'],
    primary_photo: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=400',
    location_lat: 35.9042,
    location_lng: 14.5189,
    location_name: 'Sliema Waterfront',
    breed: 'Siamese Mix',
    color: 'Cream with Blue Points',
    age: '~4 years',
    is_stray: false,
    background_story: 'Luna belongs to a local cafe owner but loves to greet visitors on the promenade.',
    voting_status: 'complete',
    voting_round_id: null,
    created_at: '2024-02-01T09:15:00Z',
    approved: true,
  },
  {
    id: '4',
    name: null,
    photos: ['/cats/cat4.jpg'],
    primary_photo: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=400',
    location_lat: 35.8781,
    location_lng: 14.5361,
    location_name: 'Three Cities',
    breed: 'Tabby',
    color: 'Grey Tabby',
    age: '~1 year',
    is_stray: true,
    background_story: 'A playful young cat often seen chasing seagulls near the waterfront.',
    voting_status: 'suggesting',
    voting_round_id: 'round-2',
    created_at: '2024-02-10T16:45:00Z',
    approved: true,
  },
  {
    id: '5',
    name: 'Cappuccino',
    photos: ['/cats/cat5.jpg'],
    primary_photo: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    location_lat: 35.8400,
    location_lng: 14.4800,
    location_name: 'Rabat',
    breed: 'Persian Mix',
    color: 'Brown and Cream',
    age: '~5 years',
    is_stray: false,
    background_story: 'This fluffy friend lives near St. Paul\'s Catacombs and loves afternoon naps.',
    voting_status: 'complete',
    voting_round_id: null,
    created_at: '2024-02-15T11:00:00Z',
    approved: true,
  },
  {
    id: '6',
    name: 'Sunny',
    photos: ['/cats/cat6.jpg'],
    primary_photo: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=400',
    location_lat: 35.9100,
    location_lng: 14.4300,
    location_name: 'Golden Bay',
    breed: 'Ginger',
    color: 'Orange',
    age: '~2 years',
    is_stray: true,
    background_story: 'Named for her love of sunbathing on the beach rocks.',
    voting_status: 'complete',
    voting_round_id: null,
    created_at: '2024-02-20T08:30:00Z',
    approved: true,
  },
];

export const sampleNameSuggestions = [
  { id: '1', cat_id: '2', suggested_name: 'Shadow', vote_count: 24 },
  { id: '2', cat_id: '2', suggested_name: 'Domino', vote_count: 18 },
  { id: '3', cat_id: '2', suggested_name: 'Mittens', vote_count: 12 },
  { id: '4', cat_id: '4', suggested_name: 'Storm', vote_count: 0 },
  { id: '5', cat_id: '4', suggested_name: 'Whiskers', vote_count: 0 },
];
